esphome:
  name: esp32c3-lpkit
  friendly_name: esp32c3-lpkit
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "SuperSecretEncryptionKeyWhichWillWorkWithHomeAssistant"

ota:
  password: "SuperSecretOTAkey"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " Fallback Hotspot"
    password: "AnotherPassword"

captive_portal:
    
