esphome:
  name: esp32c3-scd41
  friendly_name: esp32c3-scd41
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "SuperSecretKeyForHomeAssistantToWork"

i2c:
  sda: 8
  scl: 10
  scan: False
  id: bus_a
  frequency: 400kHz

sensor:
  - platform: scd4x
    i2c_id: bus_a
    address: 0x62
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

ota:
  password: "SuperSecretOTAkey"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Scd41 Fallback Hotspot"
    password: "AnotherPassword"

captive_portal:
    
